def updateText(secret_word, display_text, guess):
    updated_text=""
    for i in range(len(secret_word)):
        if secret_word[i].lower() == guess.lower():
            updated_text += guess.lower()
        else:
            updated_text += display_text[i]
    return updated_text

def hangman(secret_word):
    lives = 6
    used=""
    display_text="_" * len(secret_word)
    print("Welcome to Hangman!")
    print("Try to guess the word.")
    print(display_text)
    
    while lives > 0:
        guess = input("Guess a letter in my secret word: ")
        
        if len(guess) != 1:
            print("Please guess only ONE letter!") 
        elif not guess.isalpha():
            print("Please guess a LETTER!")
        elif guess.lower() in used:
            print("You've used this letter!")
        else:
            used += guess.lower()
            
            if guess.lower() in secret_word.lower():
                print("You've guessed a letter.")
                display_text = updateText(secret_word, display_text, guess) 
                print(display_text)
                
            else:
                lives - 1
                print("Sorry wrong guess. Lives left:", lives) 
                print(display_text)
                
    if "_" not in display_text:
        print("Congratulations! You guessed the word:", secret_word)
        break
    
    if lives 0:
        print("Sorry, you ran out of lives. The word was:", secret_word)



# Run the game with the secret word
mySecretWord "Indonesia"
hangman(mySecretWord)
